#Templates/makefile.config
#
#A template config file for make
#
#Copyright(C) 2018, Ivan Tobias Johnson
#
#LICENSE: GPL 2.0

#NOTE: this configuration file is for changes that you do NOT want to be under
#version control. If you want the changes to be added to be shared, modify the
#actual makefile.

#e.g. if a single developer uses a different compiler, they should redefine CC,
#CFLAGS, etc. in this file. If ALL developers use a different compiler, then
#just change the primary makefile.
